source ~/.bash/functions.bash || return 0
set -a
_bashrc_source_dir ~/.bash/env.d
set +a
_bashrc_source_dir ~/.bash/rc.d
if [ -n "$PS1" ]; then
  _bashrc_source_dir ~/.bash/alias.d
  _bashrc_source_dir ~/.bash/completion.d
fi
return 0


source /etc/bashrc_fitbit
export PATH="${HOME}/.local/bin:${HOME}/bin:/usr/local/gnu/bin:/usr/local/bin:/usr/local/sbin:${PATH}"
export MANPATH="/usr/local/gnu/man:/usr/local/share/man:/usr/share/man${MANPATH:+:$MANPATH}"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export JAVA_HOME='/usr/local/opt/adoptopenjdk-openjdk8'

